import os
import re
from typing import TYPE_CHECKING, Dict, List, Union

import torch
import numpy as np
import json

import sys
from pfm.conch.conch.factory import create_model_from_pretrained
from pfm.conch.conch.custom_tokenizer import get_tokenizer
from PIL import Image
from pfm.conch.conch.custom_tokenizer import tokenize
# from gliner import GLiNER

from transformers import AutoTokenizer, AutoModelForSequenceClassification
if TYPE_CHECKING:
    from swift.llm import InferRequest

import asyncio
import os
import re
import textwrap
from collections import Counter
from copy import deepcopy
from typing import Dict, List, Union

import json
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import numpy as np
# from gliner import GLiNER
import sys
sys.path.append("../../../")
from pfm.conch.conch.factory import create_model_from_pretrained
from pfm.conch.conch.custom_tokenizer import get_tokenizer, tokenize
from PIL import Image

class ORM:
    """Offline Reward Model base class."""

    def __call__(self, **kwargs) -> List[float]:
        """
        Calculates rewards for a batch of completions.

        Returns:
            A list of float rewards, one for each completion.
        """
        raise NotImplementedError


class ReactORM(ORM):
    """
    An ORM for evaluating ReAct-style agent outputs.
    It parses actions and action inputs to assess correctness.
    """

    @staticmethod
    def evaluate_action_reward(
        action_pred: list, action_ref: list, cand_list: list, ref_list: list
    ) -> bool:
        """
        Evaluates the reward for a predicted action by comparing it to the reference action.
        It considers both the action type and the action input.

        Args:
            action_pred: List of predicted action types.
            action_ref: List of reference action types.
            cand_list: List of predicted action inputs.
            ref_list: List of reference action inputs.

        Returns:
            A boolean indicating if the first prediction is correct.
        """
        f1 = []
        for i in range(len(action_pred)):
            ref_action = action_ref[i]
            pred_action = action_pred[i]

            ref_input = ref_list[i]
            cand_input = cand_list[i]

            ref_is_json = False
            try:
                ref_input_json = json.loads(ref_input)
                ref_is_json = True
            except Exception:
                ref_input_json = ref_input

            cand_is_json = False
            try:
                cand_input_json = json.loads(cand_input)
                cand_is_json = True
            except Exception:
                cand_input_json = cand_input

            if ref_action != pred_action or (ref_is_json ^ cand_is_json):
                f1.append(0)
            elif not ref_is_json and not cand_is_json:
                rougel = ReactORM.evaluate_rougel([ref_input_json], [cand_input_json])
                if rougel is None or rougel < 10:
                    f1.append(0)
                elif 10 <= rougel < 20:
                    f1.append(0.1)
                else:
                    f1.append(1)
            else:
                if not isinstance(ref_input_json, dict) or not isinstance(
                    cand_input_json, dict
                ):
                    f1.append(0)
                    continue

                half_match = 0
                full_match = 0
                if ref_input_json == {}:
                    if cand_input_json == {}:
                        f1.append(1)
                    else:
                        f1.append(0)
                else:
                    for k, v in ref_input_json.items():
                        if k in cand_input_json.keys():
                            if cand_input_json[k] == v:
                                full_match += 1
                            else:
                                half_match += 1

                    recall = (0.5 * half_match + full_match) / (
                        len(ref_input_json) + 1e-30
                    )
                    precision = (0.5 * half_match + full_match) / (
                        len(cand_input_json) + 1e-30
                    )
                    try:
                        f1.append((2 * recall * precision) / (recall + precision))
                    except Exception:
                        f1.append(0.0)

        if f1[0] == 1.0:
            return True
        else:
            return False

    @staticmethod
    def parse_action(text: str) -> (str, str):
        """
        Parses the 'Action' and 'Action Input' from a given text.

        Args:
            text: The text generated by the model.

        Returns:
            A tuple containing the action and action input.
        """
        if "Action Input:" in text:
            input_idx = text.rindex("Action Input:")
            action_input = text[input_idx + len("Action Input:") :].strip()
        else:
            action_input = "{}"

        if "Action:" in text:
            action_idx = text.rindex("Action:")
            action = text[action_idx + len("Action:") :].strip()
            if "Action Input:" in action:
                input_idx = action.index("Action Input:")
                action = action[:input_idx].strip()
        else:
            action = "none"
        return action, action_input

    @staticmethod
    def parse_output(text: str) -> (str, str):
        """
        A wrapper for parse_action to extract action and action_input.

        Args:
            text: The text generated by the model.

        Returns:
            A tuple containing the action and action input.
        """
        action, action_input = ReactORM.parse_action(text)
        return action, action_input

    def __call__(
        self,
        infer_requests: List[Union["InferRequest", Dict]],
        solution: List[str],
        **kwargs
    ) -> List[float]:
        """
        Calculates rewards for a batch of ReAct-style predictions.

        Args:
            infer_requests: A list of inference requests or raw prediction strings.
            solution: A list of ground truth solution strings.

        Returns:
            A list of float rewards.
        """
        rewards = []
        if not isinstance(infer_requests[0], str):
            predictions = [
                request["messages"][-1]["content"] for request in infer_requests
            ]
        else:
            predictions = infer_requests
        for prediction, ground_truth in zip(predictions, solution):
            if prediction.endswith("Observation:"):
                prediction = prediction[: prediction.index("Observation:")].strip()
            action_ref = []
            action_input_ref = []
            action_pred = []
            action_input_pred = []
            reference = ground_truth
            prediction = (
                prediction.replace("<|endoftext|>", "")
                .replace("<|im_end|>", "")
                .strip()
            )
            ref_action, ref_input = ReactORM.parse_output(reference)
            pred_action, pred_input = ReactORM.parse_output(prediction)
            action_ref.append(ref_action)
            action_input_ref.append(ref_input)
            if pred_action is None:
                action_pred.append("none")
            else:
                action_pred.append(pred_action)

            if pred_input is None:
                action_input_pred.append("{}")
            else:
                action_input_pred.append(pred_input)

            reward = ReactORM.evaluate_action_reward(
                action_pred, action_ref, action_input_pred, action_input_ref
            )
            rewards.append(float(reward))
        return rewards

    @staticmethod
    def evaluate_rougel(cand_list: list, ref_list: list) -> float:
        """
        Calculates the ROUGE-L F1 score.

        Args:
            cand_list: A list of candidate strings.
            ref_list: A list of reference strings.

        Returns:
            The ROUGE-L F1 score, or None if an error occurs.
        """
        if len(ref_list) == 0:
            return None
        try:
            from rouge import Rouge

            rouge = Rouge()
            rouge_score = rouge.get_scores(hyps=cand_list, refs=ref_list, avg=True)
            rougel = rouge_score["rouge-l"]["f"]
            return rougel
        except Exception:
            return None


class MathORM(ORM):
    """
    An ORM for evaluating mathematical reasoning problems.
    It can use OpenCompass's evaluator or a built-in SymPy-based method.
    """

    def __init__(self):
        """Initializes the Math ORM, optionally using the OpenCompass evaluator."""
        from transformers.utils import strtobool

        self.use_opencompass = strtobool(
            os.environ.get("USE_OPENCOMPASS_EVALUATOR", "False")
        )
        if self.use_opencompass:
            from opencompass.datasets.math import MATHEvaluator

            self.evaluator = MATHEvaluator()

    @staticmethod
    def check_terminate(answers: Union[str, List[str]]) -> List[bool]:
        """
        Checks if the answer string(s) contain the '\boxed' command, indicating a final answer.

        Args:
            answers: A single answer string or a list of them.

        Returns:
            A list of booleans indicating the presence of '\boxed'.
        """
        if isinstance(answers, str):
            answers = [answers]
        results = []
        for answer in answers:
            results.append("\\boxed" in answer)
        return results

    @staticmethod
    def extract_boxed_result(text: str) -> str:
        """
        Extracts the content from the first `\\boxed{...}` block in a string.

        Args:
            text: The string to search.

        Returns:
            The extracted content or the original text if not found.
        """
        pattern = r"\\boxed{([^}]*)}"
        match = re.search(pattern, text)
        if match:
            return match.group(1).strip()
        else:
            return text

    @staticmethod
    def clean_latex(latex_str: str) -> str:
        """
        Performs basic cleaning of a LaTeX string.

        Args:
            latex_str: The LaTeX string to clean.

        Returns:
            The cleaned string.
        """
        latex_str = re.sub(r"\\\(|\\\)|\\\\[|\\\\]", "", latex_str)
        latex_str = latex_str.replace("}}", "}").replace("{", "").replace("}", "")
        return latex_str.strip()

    @staticmethod
    def parse_expression(latex_str: str):
        """
        Parses a cleaned LaTeX string into a SymPy expression.

        Args:
            latex_str: The LaTeX string.

        Returns:
            A SymPy expression or None on failure.
        """
        from sympy import simplify
        from sympy.parsing.latex import parse_latex

        try:
            expr = parse_latex(latex_str)
            return simplify(expr)
        except Exception:
            return None

    @staticmethod
    def compare_consecutive(first: str, second: str) -> bool:
        """
        Compares two LaTeX strings for mathematical equivalence using SymPy.

        Args:
            first: The first LaTeX string.
            second: The second LaTeX string.

        Returns:
            True if they are equivalent, False otherwise.
        """
        cleaned_list = [MathORM.clean_latex(latex) for latex in [first, second]]
        parsed_exprs = [MathORM.parse_expression(latex) for latex in cleaned_list]
        if hasattr(parsed_exprs[0], "equals") and hasattr(parsed_exprs[1], "equals"):
            value = parsed_exprs[0].equals(parsed_exprs[1])
        else:
            value = parsed_exprs[0] == parsed_exprs[1]
        if value is None:
            value = False
        return value

    def __call__(
        self,
        infer_requests: List[Union["InferRequest", Dict]],
        ground_truths: List[str],
        **kwargs
    ) -> List[float]:
        """
        Calculates rewards for math problems by comparing predictions to ground truths.

        Args:
            infer_requests: A list of inference requests.
            ground_truths: A list of ground truth math solutions.

        Returns:
            A list of float rewards (1.0 for correct, 0.0 for incorrect).
        """
        rewards = []
        predictions = [request.messages[-1]["content"] for request in infer_requests]
        for prediction, ground_truth in zip(predictions, ground_truths):
            if "# Answer" in prediction:
                prediction = prediction.split("# Answer")[1]
            if "# Answer" in ground_truth:
                ground_truth = ground_truth.split("# Answer")[1]
            prediction = prediction.strip()
            ground_truth = ground_truth.strip()
            prediction = MathORM.extract_boxed_result(prediction)
            ground_truth = MathORM.extract_boxed_result(ground_truth)
            if self.use_opencompass:
                reward = self.evaluator.is_equiv(prediction, ground_truth)
            else:
                reward = MathORM.compare_consecutive(prediction, ground_truth)
            rewards.append(float(reward))
        return rewards


class MathAccuracy(ORM):
    """
    An ORM that uses the 'math_verify' library to check mathematical correctness.
    It specifically looks for answers within <answer> tags.
    """

    def __init__(self):
        """Checks for the 'math_verify' package dependency."""
        import importlib.util

        assert importlib.util.find_spec("math_verify") is not None, (
            "The math_verify package is required but not installed. "
            "Please install it using 'pip install math_verify==0.5.2'."
        )

    def __call__(self, completions, solution, **kwargs) -> List[float]:
        """
        Verifies mathematical answers using the math_verify library.

        Args:
            completions: A list of model completions.
            solution: A list of ground truth solutions.

        Returns:
            A list of float rewards.
        """
        from latex2sympy2_extended import NormalizationConfig
        from math_verify import LatexExtractionConfig, parse, verify

        rewards = []
        for content, sol in zip(completions, solution):
            content_match = re.search(r"<answer>(.*?)</answer>", content, re.DOTALL)
            content_to_parse = (
                content_match.group(1).strip() if content_match else content
            )
            has_answer_tag = content_match is not None

            sol_match = re.search(r"<answer>(.*?)</answer>", sol, re.DOTALL)
            sol_to_parse = sol_match.group(1).strip() if sol_match else sol

            gold_parsed = parse(sol_to_parse, extraction_mode="first_match")
            if len(gold_parsed) != 0:
                if has_answer_tag:
                    answer_parsed = parse(
                        content_to_parse, extraction_mode="first_match"
                    )
                else:
                    answer_parsed = parse(
                        content_to_parse,
                        extraction_config=[
                            LatexExtractionConfig(
                                normalization_config=NormalizationConfig(
                                    nits=False,
                                    malformed_operators=False,
                                    basic_latex=True,
                                    boxed=True,
                                    units=True,
                                ),
                                boxed_match_priority=0,
                                try_extract_without_anchor=False,
                            )
                        ],
                        extraction_mode="first_match",
                    )
                try:
                    reward = float(verify(gold_parsed, answer_parsed))
                except Exception:
                    reward = 0.0
            else:
                # If the gold solution is not parseable, we reward 0 to skip this example
                reward = 0.0
            rewards.append(reward)
        return rewards


class Format(ORM):
    """An ORM that rewards completions matching a specific format."""

    def __call__(self, completions, **kwargs) -> List[float]:
        """Reward function that checks if the completion has a specific format."""
        pattern = r"^<think>.*?</think>\s*<answer>.*?</answer>(?![\s\S])"
        matches = [
            re.match(pattern, content, re.DOTALL | re.MULTILINE)
            for content in completions
        ]
        return [1.0 if match else 0.0 for match in matches]


class ReActFormat(ORM):
    """An ORM that rewards completions matching a ReAct-specific format."""

    def __call__(self, completions, **kwargs) -> List[float]:
        """
        Reward function that checks if the completion has a <think>...Action...Action Input...</think> format.

        Args:
            completions: List of model completions.

        Returns:
            A list of rewards (1.0 for a match, 0.0 for no match).
        """
        pattern = r"^<think>.*?</think>\s*Action:.*?Action Input:.*?$"
        matches = [
            re.match(pattern, content, re.DOTALL | re.MULTILINE)
            for content in completions
        ]
        return [1.0 if match else 0.0 for match in matches]


class CosineReward(ORM):
    """
    Implements a cosine-based reward function based on completion length and correctness.
    This is based on the paper https://arxiv.org/abs/2502.03373.
    It encourages shorter answers for correct predictions and longer for incorrect ones.
    """

    def __init__(
        self,
        cosine_min_len_value_wrong: float = -0.5,
        cosine_max_len_value_wrong: float = 0.0,
        cosine_min_len_value_correct: float = 1.0,
        cosine_max_len_value_correct: float = 0.5,
        cosine_max_len: int = 1000,
        accuracy_orm=None,
    ):
        """
        Initializes the CosineReward ORM.

        Args:
            cosine_min_len_value_wrong: Reward for wrong answer with min length.
            cosine_max_len_value_wrong: Reward for wrong answer with max length.
            cosine_min_len_value_correct: Reward for correct answer with min length.
            cosine_max_len_value_correct: Reward for correct answer with max length.
            cosine_max_len: The maximum length for scaling.
            accuracy_orm: The accuracy ORM to determine if the answer is correct.
        """
        self.min_len_value_wrong = cosine_min_len_value_wrong
        self.max_len_value_wrong = cosine_max_len_value_wrong
        self.min_len_value_correct = cosine_min_len_value_correct
        self.max_len_value_correct = cosine_max_len_value_correct
        self.max_len = cosine_max_len
        self.accuracy_orm = accuracy_orm or MathAccuracy()

    @staticmethod
    def cosfn(t: int, T: int, min_value: float, max_value: float) -> float:
        """
        Cosine annealing function to calculate reward based on length.

        Args:
            t: Current length.
            T: Max length.
            min_value: Minimum reward value.
            max_value: Maximum reward value.

        Returns:
            The calculated reward.
        """
        import math

        return max_value - (max_value - min_value) * (1 - math.cos(t * math.pi / T)) / 2

    def __call__(self, completions, solution, **kwargs) -> List[float]:
        """
        Calculates rewards based on completion length and correctness.

        Args:
            completions: List of model completions.
            solution: List of ground truth solutions.
            **kwargs: Must contain 'response_token_ids'.

        Returns:
            A list of float rewards.
        """
        acc_rewards = self.accuracy_orm(completions, solution, **kwargs)
        response_token_ids = kwargs.get("response_token_ids")
        rewards = []
        for ids, acc_reward in zip(response_token_ids, acc_rewards):
            is_correct = acc_reward >= 1.0
            if is_correct:
                min_value = self.max_len_value_correct
                max_value = self.min_len_value_correct
            else:
                min_value = self.max_len_value_wrong
                max_value = self.min_len_value_wrong
            gen_len = len(ids)
            reward = self.cosfn(gen_len, self.max_len, min_value, max_value)
            rewards.append(reward)
        return rewards


class RepetitionPenalty(ORM):
    """
    An ORM that penalizes n-gram repetitions in the generated text.
    Based on the paper https://arxiv.org/abs/2502.03373.
    """

    def __init__(
        self,
        repetition_n_grams: int = 3,
        repetition_max_penalty: float = -1.0,
    ):
        """
        Initializes the RepetitionPenalty ORM.

        Args:
            repetition_n_grams: The size of the n-gram to check for repetitions.
            repetition_max_penalty: The maximum penalty to apply.
        """
        self.ngram_size = repetition_n_grams
        self.max_penalty = repetition_max_penalty

    @staticmethod
    def zipngram(text: str, ngram_size: int):
        """Creates n-grams from a string."""
        words = text.lower().split()
        return zip(*[words[i:] for i in range(ngram_size)])

    def __call__(self, completions, **kwargs) -> List[float]:
        """
        Reward function that penalizes repetitions.

        Args:
            completions: List of model completions.

        Returns:
            A list of float rewards (penalties).
        """
        rewards = []
        for completion in completions:
            if completion == "":
                rewards.append(0.0)
                continue
            if len(completion.split()) < self.ngram_size:
                rewards.append(0.0)
                continue

            ngrams = set()
            total = 0
            for ng in self.zipngram(completion, self.ngram_size):
                ngrams.add(ng)
                total += 1

            scaling = 1 - len(ngrams) / total
            reward = scaling * self.max_penalty
            rewards.append(reward)
        return rewards


class SoftOverlong(ORM):
    """An ORM that penalizes completions that exceed a soft maximum length."""

    def __init__(self, soft_max_length: int, soft_cache_length: int):
        """
        Initializes the SoftOverlong ORM.

        Args:
            soft_max_length: The soft maximum length threshold.
            soft_cache_length: The buffer length over which the penalty is applied.
        """
        assert soft_cache_length < soft_max_length
        self.soft_max_length = soft_max_length
        self.soft_cache_length = soft_cache_length

    def __call__(self, completions, **kwargs) -> List[float]:
        """
        Calculates a penalty for completions exceeding a soft length limit.

        Args:
            completions: List of model completions (unused, length is taken from token ids).
            **kwargs: Must contain 'response_token_ids'.

        Returns:
            A list of float rewards (penalties).
        """
        rewards = []
        response_token_ids = kwargs.get("response_token_ids")
        for ids in response_token_ids:
            completion_length = len(ids)
            expected_len = self.soft_max_length - self.soft_cache_length
            exceed_len = completion_length - expected_len
            rewards.append(min(-exceed_len / self.soft_cache_length, 0))
        return rewards


class McqORM(ORM):
    """
    An ORM for evaluating single-choice multiple-choice questions (MCQ).
    It extracts the answer from an <answer> tag and checks for equality.
    """

    def __call__(self, completions, solution, **kwargs) -> List[float]:
        """
        Reward function that checks if the predicted choice matches the solution.

        Args:
            completions (list[str]): Generated outputs from the model.
            solution (list[str]): Ground truth solution.
            **kwargs: Can contain 'task' list for multi-task support.

        Returns:
            list[float]: Reward scores (1.0 for a match, 0.0 for no match).
        """
        tasks = kwargs.get("task", [None] * len(completions))
        rewards = []
        for pred, sol, t in zip(completions, solution, tasks):
            if t not in ['mcq', 'cls']:
                rewards.append(None)
                continue

            # Extract answer from solution
            sol_match = re.search(r"<answer>(.*?)</answer>", sol, re.DOTALL)
            ground_truth = sol_match.group(1).strip() if sol_match else sol.strip()

            # Extract answer from prediction
            pred_match = re.search(r"<answer>(.*?)</answer>", pred, re.DOTALL)
            student_answer = pred_match.group(1).strip() if pred_match else pred.strip()

            # Compare the extracted answers
            if student_answer == ground_truth:
                reward = 1.0
            else:
                reward = 0.0
            rewards.append(reward)
        return rewards


class VqaBleuReward(ORM):
    """
    An ORM for evaluating VQA tasks using BLEU-4 score.
    """

    def __init__(self):
        import jieba
        from nltk.translate.bleu_score import SmoothingFunction

    def __call__(self, completions, solution, **kwargs) -> List[float]:
        import jieba
        from nltk.translate.bleu_score import SmoothingFunction,sentence_bleu

        tasks = kwargs.get("task", [None] * len(completions))
        rewards = []
        for pred, sol, t in zip(completions, solution, tasks):
            if t != 'vqa':
                rewards.append(None)
                continue

            # Extract content from <answer> tags if present
            sol_match = re.search(r"<answer>(.*?)</answer>", sol, re.DOTALL)
            reference_text = sol_match.group(1).strip() if sol_match else sol.strip()

            pred_match = re.search(r"<answer>(.*?)</answer>", pred, re.DOTALL)
            hypothesis_text = pred_match.group(1).strip() if pred_match else pred.strip()

            # Tokenize using jieba
            hypothesis = list(jieba.cut(hypothesis_text))
            reference = list(jieba.cut(reference_text))

            if not hypothesis or not reference:
                rewards.append(0.0)
                continue

            # Calculate BLEU-4
            bleu_val = sentence_bleu(
                [reference],
                hypothesis,
                smoothing_function=SmoothingFunction().method3
            )
            rewards.append(bleu_val)
        return rewards


class VqaBertReward(ORM):
    """
    An ORM for evaluating VQA tasks using BERT cosine similarity (PubMedBERT).
    """

    def __init__(self, model_name_or_path="/data/ckpt/pubmedbert-base-embeddings/"):
        self.model_name = model_name_or_path
        self.tokenizer = None
        self.model = None
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    d: float = None  # Placeholder for single line replacement if needed, but not used here.

    _global_model_cache = {}

    def _load_model(self):
        if self.model_name in VqaBertReward._global_model_cache:
            self.tokenizer, self.model = VqaBertReward._global_model_cache[self.model_name]
        else:
            from transformers import AutoTokenizer, AutoModel
            import torch
            
            print(f"Loading BERT model for reward: {self.model_name}...")
            self.tokenizer = AutoTokenizer.from_pretrained(self.model_name)
            self.model = AutoModel.from_pretrained(self.model_name).to(self.device)
            
            VqaBertReward._global_model_cache[self.model_name] = (self.tokenizer, self.model)
            self.tokenizer, self.model = VqaBertReward._global_model_cache[self.model_name]

    @staticmethod
    def meanpooling(output, mask):
        import torch
        embeddings = output[0]
        mask = mask.unsqueeze(-1).expand(embeddings.size()).float()
        return torch.sum(embeddings * mask, 1) / torch.clamp(mask.sum(1), min=1e-9)

    def __call__(self, completions, solution, **kwargs) -> List[float]:
        import torch
        import torch.nn.functional as F
        tasks = kwargs.get("task", [None] * len(completions))        
        # Check if we have any VQA tasks before loading model/processing
        has_vqa = any(t == 'vqa' for t in tasks)
        if not has_vqa:
            return [None] * len(completions)

        self._load_model()
        
        rewards = []
        for pred, sol, t in zip(completions, solution, tasks):
            if t != 'vqa':
                rewards.append(None)
                continue
            
            # Extract content from <answer> tags
            sol_match = re.search(r"<answer>(.*?)</answer>", sol, re.DOTALL)
            reference_text = sol_match.group(1).strip() if sol_match else sol.strip()

            pred_match = re.search(r"<answer>(.*?)</answer>", pred, re.DOTALL)
            hypothesis_text = pred_match.group(1).strip() if pred_match else pred.strip()

            # Calculate BERT similarity
            # Prepare inputs
            sentences = [reference_text, hypothesis_text]
            encoded_input = self.tokenizer(sentences, padding=True, truncation=True, max_length=512, return_tensors='pt')
            
            if torch.cuda.is_available():
                encoded_input = {k: v.cuda() for k, v in encoded_input.items()}

            with torch.no_grad():
                model_output = self.model(**encoded_input)

            # Pooling and Similarity
            sentence_embeddings = self.meanpooling(model_output, encoded_input['attention_mask'])
            sentence_embeddings = F.normalize(sentence_embeddings, p=2, dim=1)
            similarity = F.cosine_similarity(sentence_embeddings[0].unsqueeze(0), sentence_embeddings[1].unsqueeze(0))
            
            rewards.append(similarity.item())
        return rewards


class VqaEmbeddingReward(ORM):
    """
    An ORM for evaluating VQA tasks using embedding cosine similarity (Qwen/Qwen3-Embedding-0.6B).
    """

    def __init__(self, model_name_or_path="/data/ckpt/Qwen3-Embedding-0.6B"):
        self.model_name = model_name_or_path
        self.model = None
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    _global_model_cache = {}

    def _load_model(self):
        if self.model_name in VqaEmbeddingReward._global_model_cache:
            self.model = VqaEmbeddingReward._global_model_cache[self.model_name]
        else:
            from sentence_transformers import SentenceTransformer
            print(f"Loading Embedding model for reward: {self.model_name}...")
            # We recommend enabling flash_attention_2 for better acceleration and memory saving,
            # together with setting `padding_side` to "left":
            # self.model = SentenceTransformer(
            #     self.model_name,
            #     model_kwargs={"attn_implementation": "flash_attention_2", "device_map": "auto"},
            #     tokenizer_kwargs={"padding_side": "left"},
            # )
            self.model = SentenceTransformer(self.model_name)
            self.model = self.model.to(self.device)
            VqaEmbeddingReward._global_model_cache[self.model_name] = self.model

    def __call__(self, completions, solution, **kwargs) -> List[float]:
        tasks = kwargs.get("task", [None] * len(completions))
        # Check if we have any VQA tasks before loading model/processing
        has_vqa = any(t == 'vqa' for t in tasks)
        if not has_vqa:
            return [None] * len(completions)

        self._load_model()

        rewards = []
        for pred, sol, t in zip(completions, solution, tasks):
            if t != 'vqa':
                rewards.append(None)
                continue

            # Extract content from <answer> tags
            sol_match = re.search(r"<answer>(.*?)</answer>", sol, re.DOTALL)
            reference_text = sol_match.group(1).strip() if sol_match else sol.strip()

            pred_match = re.search(r"<answer>(.*?)</answer>", pred, re.DOTALL)
            hypothesis_text = pred_match.group(1).strip() if pred_match else pred.strip()

            # Encode with prompt_name="query" for queries
            query_embeddings = self.model.encode([hypothesis_text], prompt_name="query")
            document_embeddings = self.model.encode([reference_text])

            similarity = self.model.similarity(query_embeddings, document_embeddings)
            rewards.append(similarity.item())
        return rewards


class GeneralAccuracyReward(ORM):
    """
    A unified ORM that dispatches to specific accuracy rewards based on the task type.
    - 'mcq' / 'cls': Uses McqORM (exact string match).
    - 'vqa': Uses VqaBleuReward (BLEU-4 score).
    """

    def __init__(self, vqa_mode='bleu'):
        self.mcq_orm = McqORM()
        if vqa_mode == 'bert':
            self.vqa_orm = VqaBertReward()
        elif vqa_mode == 'embedding':
            self.vqa_orm = VqaEmbeddingReward()
        else:
            self.vqa_orm = VqaBleuReward()

    def __call__(self, completions, solution, **kwargs) -> List[float]:
        tasks = kwargs.get("task", [None] * len(completions))
        rewards = []
        
        # We need to process item by item because they might be different tasks
        # But ORMs usually take lists. 
        # For efficiency, we can split indices, but for simplicity in this loop implementation:
        
        # Actually, the underlying ORMs are implemented to return None if task doesn't match.
        # So we can just call both and coalesce the results? 
        # No, because VqaBleuReward might be expensive to run on everything if we passed the whole list.
        # Better to iterate.
        
        for i, (pred, sol, t) in enumerate(zip(completions, solution, tasks)):
            if t in ['mcq', 'cls']:
                # Call McqORM for single item
                # Wrappers to match list signature
                res = self.mcq_orm([pred], [sol], task=[t])
                rewards.append(res[0])
            elif t == 'vqa':
                # Call VqaBleuReward for single item
                res = self.vqa_orm([pred], [sol], task=[t])
                rewards.append(res[0])
            else:
                raise ValueError(f"Unsupported task type: {t}")
                
        return rewards


class AccuracyBleuReward(GeneralAccuracyReward):
    """
    Unified accuracy reward using BLEU-4 for VQA tasks.
    """
    def __init__(self):
        super().__init__(vqa_mode='bleu')

class AccuracyBertReward(GeneralAccuracyReward):
    """
    Unified accuracy reward using BERT similarity for VQA tasks.
    """
    def __init__(self):
        super().__init__(vqa_mode='bert')


class AccuracyEmbeddingReward(GeneralAccuracyReward):
    """
    Unified accuracy reward using Embedding similarity for VQA tasks.
    """
    def __init__(self):
        super().__init__(vqa_mode='embedding')



class CoTConsistencyReward(ORM):
    """
    An ORM that checks the consistency between the Chain-of-Thought (CoT) and the Answer.
    It uses a PubMedBERT model fine-tuned on MNLI to verify if the reasoning entails the answer.
    """

    def __init__(self, model_name_or_path="/data/ckpt/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext-finetuned-mnli/", min_step_ratio=0.0):
        self.model_name = model_name_or_path
        self.min_step_ratio = min_step_ratio
        self.tokenizer = None
        self.model = None
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    _global_model_cache = {}

    def _load_model(self):
        if self.model_name in CoTConsistencyReward._global_model_cache:
            self.tokenizer, self.model = CoTConsistencyReward._global_model_cache[self.model_name]
        else:
            print(f"Loading CoT Consistency model: {self.model_name}...")
            self.tokenizer = AutoTokenizer.from_pretrained(self.model_name)
            self.model = AutoModelForSequenceClassification.from_pretrained(self.model_name).to(self.device)
            self.model.eval()
            CoTConsistencyReward._global_model_cache[self.model_name] = (self.tokenizer, self.model)

    def get_prediction(self, premise, hypothesis, label_map):
        inputs = self.tokenizer(premise, hypothesis, return_tensors='pt', truncation='only_first').to(self.device)
        print(inputs)
        for k, v in inputs.items():
            print(k, v.shape)
        # raise Exception("test")
        with torch.no_grad():
            logits = self.model(**inputs).logits
            probs = logits.softmax(dim=1).cpu().numpy()[0]
        predicted_index = np.argmax(probs)
        return label_map[predicted_index], probs

    def __call__(self, completions, solution, **kwargs) -> List[float]:
        # Curriculum Learning Check
        trainer_state = kwargs.get('trainer_state')
        if trainer_state:
            current_ratio = trainer_state.global_step / trainer_state.max_steps
            if current_ratio < self.min_step_ratio:
                # Return 0.0 reward during Phase 1
                return [0.0] * len(completions)
        self._load_model()
        rewards = []
        label_map = {0: 'entailment', 1: 'neutral', 2: 'contradiction'}
        
        # Determine question/input availability
        # kwargs might contain 'query' or 'input'
        # Or we might have to rely on internal structure if provided
        queries = kwargs.get('query', [None] * len(completions))
        assert queries[0] is not None

        for idx, (pred, sol) in enumerate(zip(completions, solution)):
            # Extract CoT (<think>)
            think_match = re.search(r"<think>(.*?)</think>", pred, re.DOTALL)
            cot = think_match.group(1).strip() if think_match else ""
            
            # Extract Answer (<answer> or from solution)
            sol_match = re.search(r"<answer>(.*?)</answer>", sol, re.DOTALL)
            correct_answer = sol_match.group(1).strip() if sol_match else sol.strip()
            
            if not cot:
                rewards.append(0.0) 
                continue
            
            question = queries[idx] if isinstance(queries, list) else queries
            if not question: question = "" # Fallback
            
            print("cot:", cot)
            print("question:", question)
            print("correct_answer:", correct_answer)
            # Scheme 1
            premise1 = f"{cot}"
            hypothesis1 = f"{question}\nThe answer is {correct_answer}."
            
            # Scheme 2
            premise2 = f"{question}\n{cot}"
            hypothesis2 = f"The answer is {correct_answer}."
            
            # Scheme 3
            premise3 = f"{cot}"
            hypothesis3 = f"The answer is {correct_answer}."
            
            pred1, probs1 = self.get_prediction(premise1, hypothesis1, label_map)
            pred2, probs2 = self.get_prediction(premise2, hypothesis2, label_map)
            pred3, probs3 = self.get_prediction(premise3, hypothesis3, label_map)
            
            # Logic: If ANY is NOT contradiction, then Consistent (Reward 1.0)
            # If ALL are contradiction, then CONFLICT (Reward 0.0)
            
            # if pred1 != 'contradiction' or pred2 != 'contradiction' or pred3 != 'contradiction':
            #     rewards.append(1.0)
            # else:
            #     rewards.append(0.0)
            probs_avg = (probs1 + probs2 + probs3) / 3
            print(probs_avg) #[0.6130026  0.24925117 0.13774626]
            # max value idx:reward 0:1, 1:0, 2:-1
            rewards_val = [1, 0, -1]
            rewards.append(rewards_val[np.argmax(probs_avg)])

        return rewards


class ConchGLiNERReward(ORM):
    """
    An ORM that extracts morphological features from CoT using GLiNER and 
    calculates cosine similarity with the image using Conch.
    """

    def __init__(self, 
                 conch_model_path="/data/ckpt/conch/pytorch_model.bin",
                 min_step_ratio=0.0):
        self.conch_model_path = conch_model_path
        self.min_step_ratio = min_step_ratio
        self.conch_model = None
        self.conch_transform = None
        self.tokenizer = None 
        self.device = "cuda" if torch.cuda.is_available() else "cpu"

    _global_models = {}

    def _load_models(self):
        # Load Conch
        if 'conch' not in ConchGLiNERReward._global_models:
            print(f"Loading Conch model: {self.conch_model_path}...")
            model, transform = create_model_from_pretrained(
                model_cfg='conch_ViT-B-16',
                checkpoint_path=self.conch_model_path,
                device=self.device
            )
            model.eval()
            tokenizer = get_tokenizer()
            ConchGLiNERReward._global_models['conch'] = (model, transform, tokenizer)
            
        self.conch_model, self.conch_transform, self.tokenizer = ConchGLiNERReward._global_models['conch']

    def __call__(self, completions, solution, **kwargs) -> List[float]:
        # Curriculum Learning Check
        trainer_state = kwargs.get('trainer_state', None)
        if trainer_state:
            current_ratio = trainer_state.global_step / trainer_state.max_steps
            if current_ratio < self.min_step_ratio:
                # Return 0.0 reward during Phase 1
                return [0.0] * len(completions)
        # print("-----kwargs: ", kwargs)
        self._load_models()
        rewards = []
        
        # Check for images in kwargs
        # Assuming typical SWIFT/VLM format where `images` is a list of paths or PIL objects
        images = kwargs.get('images', [])
        if not images:
            images = kwargs.get('image_paths', [])

        for idx, pred in enumerate(completions):
            # 1. Get Image
            img_obj = None
            
            # Map completion index to image (broadcast or 1-to-1)
            # If batch size of completions matches images, 1-to-1
            # If 1 image and N completions, broadcast
            if len(images) == 1:
                img_obj = images[0]
            elif idx < len(images):
                img_obj = images[idx]
            # print("img_obj: ", img_obj)
            assert img_obj is not None
            #img_obj:  [{'bytes': None, 'path': '/data/dataset/vqa/PathMMU/images/5969f686156ee3ce9d4a298d04c2b5e78aa12809512e772c6ac34b7320f038d8.jpg'}]
            img_obj = img_obj[0]['path'] 
            assert isinstance(img_obj, str)
            img_obj = Image.open(img_obj).convert('RGB')

            # 2. Extract Morphology from CoT
            think_match = re.search(r"<think>(.*?)</think>", pred, re.DOTALL)
            cot = think_match.group(1).strip() if think_match else ""
            
            if not cot:
                cot = pred

            # print("cot: ", cot)
            # Split cot into sentences
            # morph_text = cot
            morph_text = [s.strip() for s in re.split(r'[.!?\n]', cot) if s.strip()]
            if not morph_text:
                morph_text = [cot]

            with torch.no_grad():
                # 3. Encode Image
                image_tensor = self.conch_transform(img_obj).unsqueeze(0).to(self.device)
                image_emb = self.conch_model.encode_image(image_tensor, proj_contrast=True, normalize=True)
                # print("image_emb: ", image_emb.shape)

                # 4. Encode Text
                # morph_text is a list of strings, pass directly to tokenize
                text_tokens = tokenize(texts=morph_text, tokenizer=self.tokenizer).to(self.device)
                text_emb = self.conch_model.encode_text(text_tokens)
                # print("text_emb: ", text_emb.shape)

                # 5. Similarity
                # image_emb: (1, D), text_emb: (N, D) -> sim: (N,)
                sims = torch.nn.functional.cosine_similarity(image_emb, text_emb, dim=1)
                # print("sims: ", sims.shape, sims)
                # Use average similarity of all sentences
                raw_sim = sims.mean().item()
                # print("raw_sim: ", raw_sim)

                # Scale to [0, 1]
                sim = (raw_sim + 1) / 2
                rewards.append(sim)
        return rewards

# A registry mapping names to their corresponding ORM classes.
orms = {
    "toolbench": ReactORM,
    "math": MathORM,
    "format": Format,
    "react_format": ReActFormat,
    "cosine": CosineReward,
    "repetition": RepetitionPenalty,
    "soft_overlong": SoftOverlong,
    "math_accuracy": MathAccuracy,
    "mcq": McqORM,
    "vqa_bleu": VqaBleuReward,
    "vqa_bert": VqaBertReward,
    "vqa_embedding": VqaEmbeddingReward,
    "accuracy_bleu": AccuracyBleuReward, # Explicit BLEU
    "accuracy_bert": AccuracyBertReward, # Explicit BERT
    "accuracy_embedding": AccuracyEmbeddingReward, # Explicit Embedding
    "cot_consistency": CoTConsistencyReward,
    "conch_gliner": ConchGLiNERReward,
}
