import os
import re
from typing import TYPE_CHECKING, Dict, List, Union

import json

if TYPE_CHECKING:
    from swift.llm import InferRequest


class ORM:
    """Offline Reward Model base class."""

    def __call__(self, **kwargs) -> List[float]:
        """
        Calculates rewards for a batch of completions.

        Returns:
            A list of float rewards, one for each completion.
        """
        raise NotImplementedError


class ReactORM(ORM):
    """
    An ORM for evaluating ReAct-style agent outputs.
    It parses actions and action inputs to assess correctness.
    """

    @staticmethod
    def evaluate_action_reward(
        action_pred: list, action_ref: list, cand_list: list, ref_list: list
    ) -> bool:
        """
        Evaluates the reward for a predicted action by comparing it to the reference action.
        It considers both the action type and the action input.

        Args:
            action_pred: List of predicted action types.
            action_ref: List of reference action types.
            cand_list: List of predicted action inputs.
            ref_list: List of reference action inputs.

        Returns:
            A boolean indicating if the first prediction is correct.
        """
        f1 = []
        for i in range(len(action_pred)):
            ref_action = action_ref[i]
            pred_action = action_pred[i]

            ref_input = ref_list[i]
            cand_input = cand_list[i]

            ref_is_json = False
            try:
                ref_input_json = json.loads(ref_input)
                ref_is_json = True
            except Exception:
                ref_input_json = ref_input

            cand_is_json = False
            try:
                cand_input_json = json.loads(cand_input)
                cand_is_json = True
            except Exception:
                cand_input_json = cand_input

            if ref_action != pred_action or (ref_is_json ^ cand_is_json):
                f1.append(0)
            elif not ref_is_json and not cand_is_json:
                rougel = ReactORM.evaluate_rougel([ref_input_json], [cand_input_json])
                if rougel is None or rougel < 10:
                    f1.append(0)
                elif 10 <= rougel < 20:
                    f1.append(0.1)
                else:
                    f1.append(1)
            else:
                if not isinstance(ref_input_json, dict) or not isinstance(
                    cand_input_json, dict
                ):
                    f1.append(0)
                    continue

                half_match = 0
                full_match = 0
                if ref_input_json == {}:
                    if cand_input_json == {}:
                        f1.append(1)
                    else:
                        f1.append(0)
                else:
                    for k, v in ref_input_json.items():
                        if k in cand_input_json.keys():
                            if cand_input_json[k] == v:
                                full_match += 1
                            else:
                                half_match += 1

                    recall = (0.5 * half_match + full_match) / (
                        len(ref_input_json) + 1e-30
                    )
                    precision = (0.5 * half_match + full_match) / (
                        len(cand_input_json) + 1e-30
                    )
                    try:
                        f1.append((2 * recall * precision) / (recall + precision))
                    except Exception:
                        f1.append(0.0)

        if f1[0] == 1.0:
            return True
        else:
            return False

    @staticmethod
    def parse_action(text: str) -> (str, str):
        """
        Parses the 'Action' and 'Action Input' from a given text.

        Args:
            text: The text generated by the model.

        Returns:
            A tuple containing the action and action input.
        """
        if "Action Input:" in text:
            input_idx = text.rindex("Action Input:")
            action_input = text[input_idx + len("Action Input:") :].strip()
        else:
            action_input = "{}"

        if "Action:" in text:
            action_idx = text.rindex("Action:")
            action = text[action_idx + len("Action:") :].strip()
            if "Action Input:" in action:
                input_idx = action.index("Action Input:")
                action = action[:input_idx].strip()
        else:
            action = "none"
        return action, action_input

    @staticmethod
    def parse_output(text: str) -> (str, str):
        """
        A wrapper for parse_action to extract action and action_input.

        Args:
            text: The text generated by the model.

        Returns:
            A tuple containing the action and action input.
        """
        action, action_input = ReactORM.parse_action(text)
        return action, action_input

    def __call__(
        self,
        infer_requests: List[Union["InferRequest", Dict]],
        solution: List[str],
        **kwargs
    ) -> List[float]:
        """
        Calculates rewards for a batch of ReAct-style predictions.

        Args:
            infer_requests: A list of inference requests or raw prediction strings.
            solution: A list of ground truth solution strings.

        Returns:
            A list of float rewards.
        """
        rewards = []
        if not isinstance(infer_requests[0], str):
            predictions = [
                request["messages"][-1]["content"] for request in infer_requests
            ]
        else:
            predictions = infer_requests
        for prediction, ground_truth in zip(predictions, solution):
            if prediction.endswith("Observation:"):
                prediction = prediction[: prediction.index("Observation:")].strip()
            action_ref = []
            action_input_ref = []
            action_pred = []
            action_input_pred = []
            reference = ground_truth
            prediction = (
                prediction.replace("<|endoftext|>", "")
                .replace("<|im_end|>", "")
                .strip()
            )
            ref_action, ref_input = ReactORM.parse_output(reference)
            pred_action, pred_input = ReactORM.parse_output(prediction)
            action_ref.append(ref_action)
            action_input_ref.append(ref_input)
            if pred_action is None:
                action_pred.append("none")
            else:
                action_pred.append(pred_action)

            if pred_input is None:
                action_input_pred.append("{}")
            else:
                action_input_pred.append(pred_input)

            reward = ReactORM.evaluate_action_reward(
                action_pred, action_ref, action_input_pred, action_input_ref
            )
            rewards.append(float(reward))
        return rewards

    @staticmethod
    def evaluate_rougel(cand_list: list, ref_list: list) -> float:
        """
        Calculates the ROUGE-L F1 score.

        Args:
            cand_list: A list of candidate strings.
            ref_list: A list of reference strings.

        Returns:
            The ROUGE-L F1 score, or None if an error occurs.
        """
        if len(ref_list) == 0:
            return None
        try:
            from rouge import Rouge

            rouge = Rouge()
            rouge_score = rouge.get_scores(hyps=cand_list, refs=ref_list, avg=True)
            rougel = rouge_score["rouge-l"]["f"]
            return rougel
        except Exception:
            return None


class MathORM(ORM):
    """
    An ORM for evaluating mathematical reasoning problems.
    It can use OpenCompass's evaluator or a built-in SymPy-based method.
    """

    def __init__(self):
        """Initializes the Math ORM, optionally using the OpenCompass evaluator."""
        from transformers.utils import strtobool

        self.use_opencompass = strtobool(
            os.environ.get("USE_OPENCOMPASS_EVALUATOR", "False")
        )
        if self.use_opencompass:
            from opencompass.datasets.math import MATHEvaluator

            self.evaluator = MATHEvaluator()

    @staticmethod
    def check_terminate(answers: Union[str, List[str]]) -> List[bool]:
        """
        Checks if the answer string(s) contain the '\boxed' command, indicating a final answer.

        Args:
            answers: A single answer string or a list of them.

        Returns:
            A list of booleans indicating the presence of '\boxed'.
        """
        if isinstance(answers, str):
            answers = [answers]
        results = []
        for answer in answers:
            results.append("\\boxed" in answer)
        return results

    @staticmethod
    def extract_boxed_result(text: str) -> str:
        """
        Extracts the content from the first `\\boxed{...}` block in a string.

        Args:
            text: The string to search.

        Returns:
            The extracted content or the original text if not found.
        """
        pattern = r"\\boxed{([^}]*)}"
        match = re.search(pattern, text)
        if match:
            return match.group(1).strip()
        else:
            return text

    @staticmethod
    def clean_latex(latex_str: str) -> str:
        """
        Performs basic cleaning of a LaTeX string.

        Args:
            latex_str: The LaTeX string to clean.

        Returns:
            The cleaned string.
        """
        latex_str = re.sub(r"\\\(|\\\)|\\\\[|\\\\]", "", latex_str)
        latex_str = latex_str.replace("}}", "}").replace("{", "").replace("}", "")
        return latex_str.strip()

    @staticmethod
    def parse_expression(latex_str: str):
        """
        Parses a cleaned LaTeX string into a SymPy expression.

        Args:
            latex_str: The LaTeX string.

        Returns:
            A SymPy expression or None on failure.
        """
        from sympy import simplify
        from sympy.parsing.latex import parse_latex

        try:
            expr = parse_latex(latex_str)
            return simplify(expr)
        except Exception:
            return None

    @staticmethod
    def compare_consecutive(first: str, second: str) -> bool:
        """
        Compares two LaTeX strings for mathematical equivalence using SymPy.

        Args:
            first: The first LaTeX string.
            second: The second LaTeX string.

        Returns:
            True if they are equivalent, False otherwise.
        """
        cleaned_list = [MathORM.clean_latex(latex) for latex in [first, second]]
        parsed_exprs = [MathORM.parse_expression(latex) for latex in cleaned_list]
        if hasattr(parsed_exprs[0], "equals") and hasattr(parsed_exprs[1], "equals"):
            value = parsed_exprs[0].equals(parsed_exprs[1])
        else:
            value = parsed_exprs[0] == parsed_exprs[1]
        if value is None:
            value = False
        return value

    def __call__(
        self,
        infer_requests: List[Union["InferRequest", Dict]],
        ground_truths: List[str],
        **kwargs
    ) -> List[float]:
        """
        Calculates rewards for math problems by comparing predictions to ground truths.

        Args:
            infer_requests: A list of inference requests.
            ground_truths: A list of ground truth math solutions.

        Returns:
            A list of float rewards (1.0 for correct, 0.0 for incorrect).
        """
        rewards = []
        predictions = [request.messages[-1]["content"] for request in infer_requests]
        for prediction, ground_truth in zip(predictions, ground_truths):
            if "# Answer" in prediction:
                prediction = prediction.split("# Answer")[1]
            if "# Answer" in ground_truth:
                ground_truth = ground_truth.split("# Answer")[1]
            prediction = prediction.strip()
            ground_truth = ground_truth.strip()
            prediction = MathORM.extract_boxed_result(prediction)
            ground_truth = MathORM.extract_boxed_result(ground_truth)
            if self.use_opencompass:
                reward = self.evaluator.is_equiv(prediction, ground_truth)
            else:
                reward = MathORM.compare_consecutive(prediction, ground_truth)
            rewards.append(float(reward))
        return rewards


class MathAccuracy(ORM):
    """
    An ORM that uses the 'math_verify' library to check mathematical correctness.
    It specifically looks for answers within <answer> tags.
    """

    def __init__(self):
        """Checks for the 'math_verify' package dependency."""
        import importlib.util

        assert importlib.util.find_spec("math_verify") is not None, (
            "The math_verify package is required but not installed. "
            "Please install it using 'pip install math_verify==0.5.2'."
        )

    def __call__(self, completions, solution, **kwargs) -> List[float]:
        """
        Verifies mathematical answers using the math_verify library.

        Args:
            completions: A list of model completions.
            solution: A list of ground truth solutions.

        Returns:
            A list of float rewards.
        """
        from latex2sympy2_extended import NormalizationConfig
        from math_verify import LatexExtractionConfig, parse, verify

        rewards = []
        for content, sol in zip(completions, solution):
            content_match = re.search(r"<answer>(.*?)</answer>", content, re.DOTALL)
            content_to_parse = (
                content_match.group(1).strip() if content_match else content
            )
            has_answer_tag = content_match is not None

            sol_match = re.search(r"<answer>(.*?)</answer>", sol, re.DOTALL)
            sol_to_parse = sol_match.group(1).strip() if sol_match else sol

            gold_parsed = parse(sol_to_parse, extraction_mode="first_match")
            if len(gold_parsed) != 0:
                if has_answer_tag:
                    answer_parsed = parse(
                        content_to_parse, extraction_mode="first_match"
                    )
                else:
                    answer_parsed = parse(
                        content_to_parse,
                        extraction_config=[
                            LatexExtractionConfig(
                                normalization_config=NormalizationConfig(
                                    nits=False,
                                    malformed_operators=False,
                                    basic_latex=True,
                                    boxed=True,
                                    units=True,
                                ),
                                boxed_match_priority=0,
                                try_extract_without_anchor=False,
                            )
                        ],
                        extraction_mode="first_match",
                    )
                try:
                    reward = float(verify(gold_parsed, answer_parsed))
                except Exception:
                    reward = 0.0
            else:
                # If the gold solution is not parseable, we reward 0 to skip this example
                reward = 0.0
            rewards.append(reward)
        return rewards


class Format(ORM):
    """An ORM that rewards completions matching a specific format."""

    def __call__(self, completions, **kwargs) -> List[float]:
        """Reward function that checks if the completion has a specific format."""
        pattern = r"^<think>.*?</think>\s*<answer>.*?</answer>(?![\s\S])"
        matches = [
            re.match(pattern, content, re.DOTALL | re.MULTILINE)
            for content in completions
        ]
        return [1.0 if match else 0.0 for match in matches]


class ReActFormat(ORM):
    """An ORM that rewards completions matching a ReAct-specific format."""

    def __call__(self, completions, **kwargs) -> List[float]:
        """
        Reward function that checks if the completion has a <think>...Action...Action Input...</think> format.

        Args:
            completions: List of model completions.

        Returns:
            A list of rewards (1.0 for a match, 0.0 for no match).
        """
        pattern = r"^<think>.*?</think>\s*Action:.*?Action Input:.*?$"
        matches = [
            re.match(pattern, content, re.DOTALL | re.MULTILINE)
            for content in completions
        ]
        return [1.0 if match else 0.0 for match in matches]


class CosineReward(ORM):
    """
    Implements a cosine-based reward function based on completion length and correctness.
    This is based on the paper https://arxiv.org/abs/2502.03373.
    It encourages shorter answers for correct predictions and longer for incorrect ones.
    """

    def __init__(
        self,
        cosine_min_len_value_wrong: float = -0.5,
        cosine_max_len_value_wrong: float = 0.0,
        cosine_min_len_value_correct: float = 1.0,
        cosine_max_len_value_correct: float = 0.5,
        cosine_max_len: int = 1000,
        accuracy_orm=None,
    ):
        """
        Initializes the CosineReward ORM.

        Args:
            cosine_min_len_value_wrong: Reward for wrong answer with min length.
            cosine_max_len_value_wrong: Reward for wrong answer with max length.
            cosine_min_len_value_correct: Reward for correct answer with min length.
            cosine_max_len_value_correct: Reward for correct answer with max length.
            cosine_max_len: The maximum length for scaling.
            accuracy_orm: The accuracy ORM to determine if the answer is correct.
        """
        self.min_len_value_wrong = cosine_min_len_value_wrong
        self.max_len_value_wrong = cosine_max_len_value_wrong
        self.min_len_value_correct = cosine_min_len_value_correct
        self.max_len_value_correct = cosine_max_len_value_correct
        self.max_len = cosine_max_len
        self.accuracy_orm = accuracy_orm or MathAccuracy()

    @staticmethod
    def cosfn(t: int, T: int, min_value: float, max_value: float) -> float:
        """
        Cosine annealing function to calculate reward based on length.

        Args:
            t: Current length.
            T: Max length.
            min_value: Minimum reward value.
            max_value: Maximum reward value.

        Returns:
            The calculated reward.
        """
        import math

        return max_value - (max_value - min_value) * (1 - math.cos(t * math.pi / T)) / 2

    def __call__(self, completions, solution, **kwargs) -> List[float]:
        """
        Calculates rewards based on completion length and correctness.

        Args:
            completions: List of model completions.
            solution: List of ground truth solutions.
            **kwargs: Must contain 'response_token_ids'.

        Returns:
            A list of float rewards.
        """
        acc_rewards = self.accuracy_orm(completions, solution, **kwargs)
        response_token_ids = kwargs.get("response_token_ids")
        rewards = []
        for ids, acc_reward in zip(response_token_ids, acc_rewards):
            is_correct = acc_reward >= 1.0
            if is_correct:
                min_value = self.max_len_value_correct
                max_value = self.min_len_value_correct
            else:
                min_value = self.max_len_value_wrong
                max_value = self.min_len_value_wrong
            gen_len = len(ids)
            reward = self.cosfn(gen_len, self.max_len, min_value, max_value)
            rewards.append(reward)
        return rewards


class RepetitionPenalty(ORM):
    """
    An ORM that penalizes n-gram repetitions in the generated text.
    Based on the paper https://arxiv.org/abs/2502.03373.
    """

    def __init__(
        self,
        repetition_n_grams: int = 3,
        repetition_max_penalty: float = -1.0,
    ):
        """
        Initializes the RepetitionPenalty ORM.

        Args:
            repetition_n_grams: The size of the n-gram to check for repetitions.
            repetition_max_penalty: The maximum penalty to apply.
        """
        self.ngram_size = repetition_n_grams
        self.max_penalty = repetition_max_penalty

    @staticmethod
    def zipngram(text: str, ngram_size: int):
        """Creates n-grams from a string."""
        words = text.lower().split()
        return zip(*[words[i:] for i in range(ngram_size)])

    def __call__(self, completions, **kwargs) -> List[float]:
        """
        Reward function that penalizes repetitions.

        Args:
            completions: List of model completions.

        Returns:
            A list of float rewards (penalties).
        """
        rewards = []
        for completion in completions:
            if completion == "":
                rewards.append(0.0)
                continue
            if len(completion.split()) < self.ngram_size:
                rewards.append(0.0)
                continue

            ngrams = set()
            total = 0
            for ng in self.zipngram(completion, self.ngram_size):
                ngrams.add(ng)
                total += 1

            scaling = 1 - len(ngrams) / total
            reward = scaling * self.max_penalty
            rewards.append(reward)
        return rewards


class SoftOverlong(ORM):
    """An ORM that penalizes completions that exceed a soft maximum length."""

    def __init__(self, soft_max_length: int, soft_cache_length: int):
        """
        Initializes the SoftOverlong ORM.

        Args:
            soft_max_length: The soft maximum length threshold.
            soft_cache_length: The buffer length over which the penalty is applied.
        """
        assert soft_cache_length < soft_max_length
        self.soft_max_length = soft_max_length
        self.soft_cache_length = soft_cache_length

    def __call__(self, completions, **kwargs) -> List[float]:
        """
        Calculates a penalty for completions exceeding a soft length limit.

        Args:
            completions: List of model completions (unused, length is taken from token ids).
            **kwargs: Must contain 'response_token_ids'.

        Returns:
            A list of float rewards (penalties).
        """
        rewards = []
        response_token_ids = kwargs.get("response_token_ids")
        for ids in response_token_ids:
            completion_length = len(ids)
            expected_len = self.soft_max_length - self.soft_cache_length
            exceed_len = completion_length - expected_len
            rewards.append(min(-exceed_len / self.soft_cache_length, 0))
        return rewards


class McqORM(ORM):
    """
    An ORM for evaluating single-choice multiple-choice questions (MCQ).
    It extracts the answer from an <answer> tag and checks for equality.
    """

    def __call__(self, completions, solution, **kwargs) -> List[float]:
        """
        Reward function that checks if the predicted choice matches the solution.

        Args:
            completions (list[str]): Generated outputs from the model.
            solution (list[str]): Ground truth solutions.

        Returns:
            list[float]: Reward scores (1.0 for a match, 0.0 for no match).
        """
        rewards = []
        for pred, sol in zip(completions, solution):
            # Extract answer from solution
            sol_match = re.search(r"<answer>(.*?)</answer>", sol, re.DOTALL)
            ground_truth = sol_match.group(1).strip() if sol_match else sol.strip()

            # Extract answer from prediction
            pred_match = re.search(r"<answer>(.*?)</answer>", pred, re.DOTALL)
            student_answer = pred_match.group(1).strip() if pred_match else pred.strip()

            # Compare the extracted answers
            if student_answer == ground_truth:
                reward = 1.0
            else:
                reward = 0.0
            rewards.append(reward)
        return rewards


# A registry mapping names to their corresponding ORM classes.
orms = {
    "toolbench": ReactORM,
    "math": MathORM,
    "accuracy": MathAccuracy,
    "format": Format,
    "react_format": ReActFormat,
    "cosine": CosineReward,
    "repetition": RepetitionPenalty,
    "soft_overlong": SoftOverlong,
    "mcq": McqORM,
}
